name: Wisecow CI/CD

on:
  push:
    branches:
      - main   # run on main branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/wisecow:latest .
          docker push ${{ secrets.DOCKERUSERNAME }}/wisecow:latest

      # Set up kubectl
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/wisecow-deployment.yaml
          kubectl apply -f k8s/wisecow-service.yaml
